# seed
seed: 42 # 19980406

# tokenizer
max_length            : 128 # 256
num_hard_negative_ctx : 10 # 30
num_other_negative_ctx: 10 # 30

# dataset
train_file: /kaggle/input/dpr-20pct-data/retriever/nq-train.json
val_file  : /kaggle/input/dpr-20pct-data/retriever/nq-dev.json
num_workers    : 4
prefetch_factor: 2

# model
base_model: bert-base-uncased

# train
train_bs_per_device  : 4 # 16
val_bs_per_device    : 2 # 8
grad_accumulate_steps: 4 # 1, note: tăng này thì phải giảm lr

epochs: 20 # 40
max_grad_norm: 1.0
val_interval: 2.0

# optimizer
lr          : 2.0e-5
weight_decay: 0.0
adam_eps    : 1.0e-8 # epsilon, dùng để tránh chia cho 0 trong tính toán
warmup_steps: 400 # 1237