wiki_file : downloads/sample_5pct_data/wikipedia_split/psgs_w100.tsv
num_docs  : 1050766 # 21015324
num_shards: # 8

nq_test_file: downloads/sample_5pct_data/retriever/qas/nq-test.csv
encoding_bs : 16 # 32
max_length  : 128 # 256

pretrained_model: trained/step-368/doc_encoder